Algoritmo "EXP001"

// Desenvolver um progra de computador que efetue a leitura de dois números
// inteiros. Processe a operação de adição de dois valores e apresente na
// sequencia a soma obtida com a operação

Var

  X, A, B : inteiro

Inicio

   Escreva("Digite o 1º número: ")
   Leia(A)
   
   
   Escreva("Digite o 2º número: ")
   Leia(B)
   
   X <- A + B
   
   Escreva("SOMA = ", X)

Fimalgoritmo