Algoritmo "EXP001"

// Desenvolver um programa de computador que calcule o reajuste de salário de
// um colaborador de uma empresa. Considere que o colaborador deve receber um
// reajuste de 15% caso seu salário seja menor que 500. Se o salário for maior
// ou igual a 500, mas menor ou igual a 1000, seu reajuste será de 10%; caso
// seja ainda maior que 1000, o reajuste deve ser de 5%

Var

   SA, NS : ReaL


Inicio



Fimalgoritmo